name: lando-drupal8 # this can be removed when we release the new lando 3.17.x cli
excludes:
  - core
  - vendor
config:
  drush: false
events:
  post-start:
    - appserver: env | grep "PATH" | grep "/app/vendor/bin"
    - appserver: /app/vendor/bin/drush status || drush status
services:
  appserver:
    build:
      - composer require -n drush/drush:10.2.1
plugins:
  "@lando/drupal": ./../../../
