name: Drupal Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        leia-test:
          - examples/drupal-custom
          - examples/drupal-defaults
          - examples/drupal-export
          - examples/drupal-import
          - examples/drupal-mariadb
          - examples/drupal-mariadb-mysql
          - examples/drupal-mysql8
          - examples/drupal-nginx
          - examples/drupal6
          - examples/drupal7
          - examples/drupal8
          - examples/drupal9
          - examples/drupal10
          - examples/drupal10-mysql8
          - examples/drupal10-nginx
          - examples/drupal11
          - examples/drupal11-mysql84
          - examples/drupal11-nginx
        lando-version:
          - 3-edge
          - 3-stable
        os:
          - ubuntu-24.04
        node-version:
          - '20'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install NPM dependencies
        run: npm clean-install --production
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v3
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/drupal=/home/runner/work/drupal/drupal
          telemetry: false
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
