name: Drupal Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        leia-test:
          - examples/drupal6
          - examples/drupal7
          - examples/drupal8
          - examples/drupal9
          - examples/drupal10
          - examples/drupal10-mysql8
        lando-version:
          - 3-dev
        os:
          - ubuntu-22.04
        node-version:
          - '16'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v2
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            plugins.@lando/drupal=/home/runner/work/drupal/drupal
          telemetry: false
      - name: Verify Lando works and we are dogfooding this plugin for tests
        run: |
          lando --clear
          lando version
          lando config --path plugins | grep drupal | grep /home/runner/work/drupal/drupal || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
